name: Docker Image CI

on:
 workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag nodehello:latest
    - name: Test the Dockerfile
      run: docker run -itd --name nodetest -p 3000:3000 nodehello:latest
    - name: Run the Dockerfile
      run: sleep 5 && curl localhost:3000
